name: Usage Pandoc-Extra

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: create output folder
        run: |
          mkdir output
      - uses: docker://pandoc/extra:3.8
        with:
          args: >-  # break string of arguments into multiple lines
            README.md --output=output/README.pdf
            --standalone
            --template /.pandoc/templates/eisvogel.latex
            --listings
            -V block-headings
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
